### ISSUE TITLE
Updated ReadMe

### ISSUE THREAD

**Issue by SmithJK** [GRIFFINCollaboration/detectorSimulations_v10#10]
Could the ReadMe please be updated? It looks like it was just copied over from the detectorSimulations package and hasn't been updated since. As an example, there isn't a `dataRootClass` directory anymore.

**Comment by VinzenzBildstein** [comment]
I've updated the README a little bit, mainly changing detectorSimulations to detectorSimulations_v10, and removing some obsolete instructions. I haven't checked whether the list of commands is still up to date, I know there are some commands missing (mostly for DESCANT), but more might have been changed.

**Comment by SmithJK** [comment]
Thanks.
