### ISSUE TITLE
NDA files

### ISSUE THREAD

**Issue by SmithJK** [GRIFFINCollaboration/detectorSimulations_v10#12]
In order to compile, I had to remove some header inclusion statements and add in some new ones from the NDA suppressed files. I'm using 10.01.p03. Now I'm having some problems running the included 60Co example - mostly with G4Tubs exception errors related to the tank object and more specifically, the `coolant_thickness` variable. It's getting to the point where I think all of these errors are telling me I did something wrong earlier in the process.

Does this sound familiar to anyone?

**Comment by VinzenzBildstein** [comment]
We've had no problems compiling it here with 10.01.p02 (including Evan's Correlation code) and 10.02 (without Evan's code). What header inclusion statements did you have to change, and are you using Evan's code?

**Comment by SmithJK** [comment]
In order to compile, I had to removed some header file inclusions from the NDA files:
#include "DetectionSystemGammaTracking.hh"
#include "ApparatusGenericTarget.hh"
#include "ApparatusSpiceTargetChamber.hh"
#include "ApparatusFieldBox.hh"

I also had to add two head files:
#include "G4SystemOfUnits.hh"
#include "G4PhysicalConstants.hh"

and modify one line (:line 871):
vacuum_chamber_sphere_log(0) to vacuum_chamber_aux_sphere_log(0)

Are my NDA files different from the Guelph files?

**Comment by VinzenzBildstein** [comment]
Might be. I'll send you the version we're using here.

**Comment by SmithJK** [comment]
Yes, those are different.

**Comment by SmithJK** [comment]
Now everything compiles and runs.
