### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by cnatzke** [GRIFFINCollaboration/detectorSimulations_v10#19]
Upon running the `make` command I receive the following error 
```
[ 97%] Building CXX object CMakeFiles/Griffinv10.dir/src/DetectorConstructionSuppressed.cc.o                                              
make[2]: *** No rule to make target `/usr/lib64/libQtOpenGL.so', needed by `Griffinv10'.  Stop.
make[1]: *** [CMakeFiles/Griffinv10.dir/all] Error 2
make: *** [all] Error 2
```
Has anyone seen this error before?

**Comment by r3dunlop** [comment]
Do you have OpenGL or Qt installed on your computer?

On Jul 26, 2016, at 12:53 PM, cnatzke <notifications@github.com<mailto:notifications@github.com>> wrote:


Upon running the make command I receive the following error

[ 97%] Building CXX object CMakeFiles/Griffinv10.dir/src/DetectorConstructionSuppressed.cc.o
make[2]: *** No rule to make target `/usr/lib64/libQtOpenGL.so', needed by `Griffinv10'.  Stop.
make[1]: *** [CMakeFiles/Griffinv10.dir/all] Error 2
make: *** [all] Error 2


Has anyone seen this error before?

**Comment by cnatzke** [comment]
Yeah, I fixed the issue. I did not have the correct symlink. Thanks for the reply though!
