### ISSUE TITLE
Issue with GRIFFIN detection system and Geant4.10.3

### ISSUE THREAD

**Issue by jturko** [GRIFFINCollaboration/detectorSimulations_v10#23]
There is a segmentation fault that occurs when trying to build the GRIFFIN detectors while using the newest version of Geant4 (4.10.3 - no_patch). Haven't looked into this any further.

**Comment by VinzenzBildstein** [comment]
I just compiled the newest version of the simulation with Gean4.10.03 and it ran w/o crashing. I haven't tried running it repeatedly, so this might be an intermittent issue. 

I will close this issue for now (might re-open it if we find other issues or instances where 10.03 or 10.04 don't work).

It did however run much slower (140 minutes vs. 3-4 minutes).
