### ISSUE TITLE
Seg Fault when Running with Angular Correlation Patch

### ISSUE THREAD

**Issue by rcoleman48** [GRIFFINCollaboration/detectorSimulations_v10#34]
There is an issue running Griffinv10 when using geant4.10.01.p03 with the angular correlation patch on top of it. Running a macro from either the command line or the UI causes a segmentation fault. However this issue only occurs when running in the build directory. So the following line causes a seg fault
./Griffinv10 /Path/to/run.mac
However if not in the build directory the following runs correctly
/Path/to/Griffinv10 /Other/Path/run.mac

**Comment by VinzenzBildstein** [comment]
I think anyone this might be relevant to has seen this. Also since we don't advise using geant4.10.01 anymore, I'm going to close this issue.
I've compiled the newest version both with geant4.10.01 and geant4.10.02 and had no problems running macros from within the build directory.
