### ISSUE TITLE
Update README: Geant4.10.1 issue

### ISSUE THREAD

**Issue by jhenderson88** [GRIFFINCollaboration/detectorSimulations_v10#35]
There is an issue with gamma-decay schemes in Geant4.10.01. 
See: http://hypernews.slac.stanford.edu/HyperNews/geant4/get/hadronprocess/1498/1.html
"Concerning gamma deexcitation, Geant4 10.1 is basically wrong, even patched."

This resulted in (for example) a 152Eu spectrum that was completely wrong, even with a correct input file.

It has been corrected in 4.10.02. The readme should be updated to mention this, especially as 4.10.01 is the version mentioned.

**Comment by VinzenzBildstein** [comment]
Fixed in PR #36.
