### ISSUE TITLE
60Co Simulation Broken

### ISSUE THREAD

**Issue by cbray0** [GRIFFINCollaboration/detectorSimulations_v10#52]
The 60Co example simulation is broken in the Geant4.10.04 branch. Using the example macro, the simulation aborts after throwing this exception:
(I have checked that the PhotonEvaporation dataset was installed correctly with Geant4 and that the environment variable was properly set. )

```
/grdm/setPhotoEvaporationFile 28 60 UserData/UserEvapData_z28.a60

-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : had014
      issued by : G4LevelReader::LevelManager(..)
 G4LevelReader: wrong data file for Z= 28 A= 60 level #0 has index 1
Check G4LEVELGAMMADATA

*** Fatal Exception *** core dump ***
-------- EEEE -------- G4Exception-END --------- EEEE -------


*** G4Exception: Aborting execution ***
Aborted (core dumped)
```

When I replace the UserEvapData file with the version located in `geant4.10.04/install/share/Geant4-10.4.1/data/PhotonEvaporation5.2/z28.a60`, the simulation runs without throwing the exception. However, the resulting `g4out.root` (any any `g4out_t[0-9]*.root`) files contain no data. The `ntuple;1` folder and the usual ntuple objects are all present, but they contain no data.

**Comment by VinzenzBildstein** [comment]
I ran the geant4.10.04 branch with a modified 60Co.mac script without problems.
Differences were that in my script the following lines were commented out:
#/grdm/setRadioactiveDecayFile 27 60 UserData/UserRadData_z27.a60
#/grdm/setPhotoEvaporationFile 28 60 UserData/UserEvapData_z28.a60
#/grdm/nucleusLimits 60 60 27 27
and the lines putting SCEPTAR, the vacuum chamber, and the delrin sphere were put back in. I also added the line
/process/deex/correlatedGamma true
to see if the angular correlations were working, but the simulation also ran w/o that line.

**Comment by VinzenzBildstein** [comment]
It is not surprising btw that the old user data files do not work anymore as the format has been changed. I don't want to change the example script yet, as this branch hasn't been fully tested yet.

**Comment by VinzenzBildstein** [comment]
I just re-ran the macro with the newest version of the code, and it worked fine. I used both my modified 60Co.mac, as well as the example one with only the two user data lines commented out:
```
#/grdm/setRadioactiveDecayFile 27 60 UserData/UserRadData_z27.a60
#/grdm/setPhotoEvaporationFile 28 60 UserData/UserEvapData_z28.a60
```

**Comment by cbray0** [comment]
It appears that, with those lines removed, the simulation runs correctly. Thanks!
