### ISSUE TITLE
Geant4.10.2

### ISSUE THREAD

**Issue by jturko** [GRIFFINCollaboration/detectorSimulations_v10#6]
The Griffin code does not compile as-is on the newest version of Geant (4.10.2); an error comes from the missing G4ComponentGGNuclNuclXsc.hh file. The reason is stated in the release notes (http://geant4.cern.ch/support/ReleaseNotes4.10.2.html) under hadronic processes:

"Deleted old classes G4GlauberGribovCrossSection, G4GGNuclNuclCrossSection, and replaced them with new, recommended ones G4ComponentGGHadronNucleusXsc and G4ComponentGGNuclNuclXsc, respectively."

I have gone back to using the previous release (4.10.1-patch02) where the code should compile, but some tweaking will need to be made to make the code compatible with the newer version of Geant4.

**Comment by SmithJK** [comment]
Any update on this?

**Comment by AndrewMac1** [comment]
There hasn't been any further work done with this yet, I believe Joey is going to do some investigating once he is done his exams (a week or two). I guess I should also say that they have implemented (at least part of) their own methods for angular correlations in this version. Once we get back from a workshop I will give people an update and start testing. We may be able simply use theirs and not require Evan's add on.

**Comment by matjones67** [comment]
Hey there, I'm Kyle's new PhD student, and I've just started working with Geant4. I ran into this issue, and did some digging. I think that I've got a fix. The only errors that crop up are from the headers called in the PhysicsList.cc source file. I changed the header call on L71 to G4ComponentGGNuclNuclXsc.hh and the type declaration on L263 to G4VCrossSectionDataSet. I've done side-by-side comparisons of results (using the included examples) from build Geant4.10.1.3 and Geant4.10.2.1 and as far as I can tell, they are the same.

I've attached a copy of the src directory (sans suppressed files)


[src.tar.gz](https://github.com/GRIFFINCollaboration/detectorSimulations_v10/files/226856/src.tar.gz)

**Comment by r3dunlop** [comment]
Welcome.
Have you been able to fork and sync these changes up on github? You could then do a pull request where people can easily see the changes that have been made as well easily sync it up to the main code.

**Comment by jturko** [comment]
My last pull request includes the changes to PhysListHadron.cc that should work for both Geant4.10.1 and Geant4.10.2, as recommended in matjones67 comment.

**Comment by VinzenzBildstein** [comment]
Thanks @jturko
