### ISSUE TITLE
geant4.10.07.p04 installation

### ISSUE THREAD

**Issue by Abi-12308** [GRIFFINCollaboration/detectorSimulations_v10#80]
Hi, I am trying to install geant4.10.07.p04 on centos 7 machine, when I run "make -j4" I got the following error messages

/home/aavaa/softwares/geant4/geant4.10.07.p04/source/externals/ptl/include/PTL/TaskGroup.hh:125:24: error: function ‘PTL::JoinFunction<void, void>::

/home/aavaa/softwares/geant4/geant4.10.07.p04/source/externals/ptl/include/PTL/TaskGroup.hh:61:15: error: function ‘PTL::JoinFunction<void, void>& P 

Any idea?

**Comment by VinzenzBildstein** [comment]
Sorry, but that is a question for the geant4 forum, not the GRIFFIN detector simulation.
