### ISSUE TITLE
Setting Detectors to 145mm Full Suppression Mode

### ISSUE THREAD

**Issue by cnatzke** [GRIFFINCollaboration/detectorSimulations_v10#85]
I just want to make sure I understand what my macro is telling to simulation to do. I would like to have the crystals at 145mm with full Compton Suppression. Reading the comments in the example macros the below code should have the full shields correct? 

More accurately this places the array in optimized peak-to-total mode correct?
```
#--- Detector Properties ---------------------------------------------
/DetSys/det/SetCustomRadialDistance 11 cm
/DetSys/det/SetCustomShieldsPresent 1
/DetSys/det/SetCustomExtensionSuppressorLocation 1
```

**Comment by VinzenzBildstein** [comment]
The first line after the comment says quite clearly that the radial distance of the detector is 11 cm, aka 110 mm.

**Comment by cnatzke** [comment]
Yes it does. The comments in the example macro `60Co.mac` say to leave it as 11 cm regardless.
```
###################### GRIFFIN DETECTOR PROPERTIES ######################################
#SetCustomShieldsPresent 1 (include suppressors)
#SetCustomShieldsPresent 0 (do NOT include suppressors)
#SetCustomShieldsPresent -1 (only include side and back suppressors, ie. no extension)
#SetCustomRadialDistance 11 cm (leave this at 11 cm, even in back mode)
#SetCustomExtensionSuppressorLocation 0 (forward mode)
#SetCustomExtensionSuppressorLocation 1 (back mode)
#includeGriffinHevimet 0 (no)
#includeGriffinHevimet 1 (yes)
```

**Comment by VinzenzBildstein** [comment]
Interesting. In that case I would guess that the best way to check this would be to run the simulation with a visualizer and see if there's any overlap between the suppressors and the detectors if you run it like that?

**Comment by VinzenzBildstein** [comment]
I had some time to look into the code, and it looks like the backshift of 3.5 cm is automatically added to the radial distance when using SetCustomExtensionSuppressorLocation 1 (the "back mode" comment seems to apply to GRIFFIN, not the suppressors). So your macro would seem to be correct for using full Compton suppression.
